[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
mini_ncn = "FMtP7JSgYneYu36nisXubFWTWw6LGC9EFJ6YhjAq6CQr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bun run -b ts-mocha ./tsconfig.json -t 1000000 tests/*.ts"

[test]
startup_wait = 3000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "RestkWeAVL8fRGgzhfeoqFhsqKRchg6aa1XrcH96z4Q"
program = "../fixtures/jito_restaking_program.so"

[[test.genesis]]
address = "Vau1t6sLNxnzB7ZDsef8TLbPLfyZMYXH8WTNqUdm9g8"
program = "../fixtures/jito_vault_program.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "../fixtures/noop.so"

[[test.genesis]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "../fixtures/spl_account_compression.so"
